# Bergische Universität Wuppertal #

**Fakultät Mathematik und Naturwissenschaften** 

**Angewandte Mathematik/Numerische Analysis**

*Dr. L. Teng*

*L. Kapllani, M.Sc.* 

*Summerterm 2021*


# Computational Finance I
**Lab-Exercise No. 1**


# P1: Trinomial Tree
In the lecture we mentioned that a binomial model can be generalized to a trinomial model. In a trinomial model we need to consider three stock price developments: in one period the price increases by a factor of $u$ with the probability $p_u$, descreases by a factor of $d$ with the probability $p_d$, or remains unchanged with the probability $1−p_u −p_d$. The trinomial model can be built in a similar way to the binomial model, e.g., by matching the expectation and the variance and using $ud = 1$ we obtain:
    $$ u = e^{\sigma\sqrt{2\Delta t}}, \quad d = e^{-\sigma\sqrt{2\Delta t}}, \quad p_d = \left( \frac{ e^{\sigma\sqrt{\frac{\Delta t}{2}}} - e^{r\frac{\Delta t}{2}} }{e^{\sigma\sqrt{\frac{\Delta t}{2}}} - e^{-\sigma\sqrt{\frac{\Delta t}{2}}}} \right)^2, \quad \quad p_u = \left( \frac{ e^{r\frac{\Delta t}{2}} - e^{-\sigma\sqrt{\frac{\Delta t}{2}}}}{e^{\sigma\sqrt{\frac{\Delta t}{2}}} - e^{-\sigma\sqrt{\frac{\Delta t}{2}}}} \right)^2.$$

For the programming task write the corresponding Python functions that are asked in each section below.

**Return the solutions of the programming task $\href{https://moodle.uni-wuppertal.de/mod/assign/view.php?id=762093}{{here}}$ until Friday, May 21. The assignment can be done in groups of 1-2 persons. The solution should be presented within the following 2 weeks via an online arranged ZOOM meeting with M.Sc. Lorenc Kapllani.**

## Write your data

In [2]:
print("First Name: Aleksandar")
print("Sure Name: Mitic")
print("Matriculation number: 2035177")
print("E-mail: aleksandar.mitic@uni-wuppertal.de")
print("Degree Type: Master ")
print("Degree Name: Master of science")

First Name: Aleksandar
Sure Name: Mitic
Matriculation number: 2035177
E-mail: aleksandar.mitic@uni-wuppertal.de
Degree Type: Master 
Degree Name: Master of science


## Import all necessary modules

In [3]:
import math
import numpy as np

## Test Parameters

In [4]:
# Input parameters
sigma = 0.2
K = 100
S0 = 100
N = 4
r = 0.05
T = 1
d_t = T / N

# Start coding
**Note:** 
* Add code where you find the comment "# Add code here"
* Get the same output as it is presented in the Markdown text **Expected Output:**

## Define a function to calculate the up and down factors

In [5]:
def calc_ud(sigma, d_t):
    """
    Function that calculates the factors in the trinomial model

    Input: sigma -> volatility 
            d_t  -> time step size

    Output: u -> upward movement
            d -> downward movement

    """
    # Add code here
    a=math.exp(sigma*math.sqrt(2*d_t));
    b=math.exp(-sigma*math.sqrt(2*d_t));
    u=round(a,10);
    d=round(b,10);
    return u,d

In [6]:
# Calculate upward and downward movements
# Add code here
u, d = calc_ud(sigma, d_t)
print('u = %.6f, d = %.6f' % (u, d))

u = 1.151910, d = 0.868123


**Expected Output:**
`u = 1.151910, d = 0.868123`

## Define a function to calculate the probabilities in the trinomial model

In [7]:
def calc_prob(r, sigma, d_t):
    """
    Function that calculates the probabilities in the trinomial model

    Input: r     -> interest rate
           sigma -> volatility
           d_t   -> time step size

    Output: p_u -> probability for upward movement
            p_d -> probability for downward movement
            p_m -> probability for no change

    """
    # Add code here
    a=((math.exp(sigma*math.sqrt(d_t/2))-math.exp(r*(d_t/2)))/(math.exp(sigma*math.sqrt(d_t/2))-math.exp(-sigma*math.sqrt(d_t/2))))**2
    b=((math.exp(r*(d_t/2))-math.exp(-sigma*math.sqrt(d_t/2)))/(math.exp(sigma*math.sqrt(d_t/2))-math.exp(-sigma*math.sqrt(d_t/2))))**2
    c=1-b-a;
    p_u=round(b,10);
    p_d=round(a,10);
    p_m=round(c,10);
    return p_u,p_d,p_m

In [8]:
# Calculate probabilities
# Add code here
p_u, p_d, p_m = calc_prob(r, sigma, d_t)
print('p_u = %.6f, p_d = %.6f, p_m = %.6f' % (p_u, p_d, p_m))

p_u = 0.277334, p_d = 0.224084, p_m = 0.498582


**Expected Output:**
`p_u = 0.277334, p_d = 0.224084, p_m = 0.498582`

## Define a function to calculate the stock prices in the trinomial model

In [9]:
def stock_price_trinom(S0, N, u, d):
    
    """
    Function that calculates the stock prices in the trinomial model
    
    Input: S0 -> Initial Stock Price
           u  -> upward movement
           d  -> downward movement
           N  -> Number of time periods
       
    Output: S -> Upper triangular matrix of Stock prices with tirnomial model
    """
    # Add code here
    S = np.zeros((N*2+1,N+1))
    S[0,0]=S0
    for i in range(N*2+1):
        for j in range(0,N+1):
            if i==j:
                S[j,i]=S0
            #elif j-i>0:
            #    S[i,j]=round((u**(j-i))*S0,8)
            elif i-j<=j: # d=1/u
            #i-j>0 and i-j<=j:
                S[i,j]=round((d**(i-j))*S0,8)                         
    return S

In [10]:
# Calculate stock prices
# Add code here
u= 1.15190991017
d= 0.86812344539
S=stock_price_trinom(S0, N, u, d)
print("Stock Prices")
print(S)

Stock Prices
[[100.         115.19099102 132.68964412 152.84651603 176.06541656]
 [  0.         100.         115.19099102 132.68964412 152.84651603]
 [  0.          86.81234454 100.         115.19099102 132.68964412]
 [  0.           0.          86.81234454 100.         115.19099102]
 [  0.           0.          75.36383164  86.81234454 100.        ]
 [  0.           0.           0.          75.36383164  86.81234454]
 [  0.           0.           0.          65.42510918  75.36383164]
 [  0.           0.           0.           0.          65.42510918]
 [  0.           0.           0.           0.          56.7970712 ]]


**Expected Output:**

`Stock Prices`

`[[100.         115.19099102 132.68964411 152.84651603 176.06541655]
 [  0.         100.         115.19099102 132.68964411 152.84651603]
 [  0.          86.81234454 100.         115.19099102 132.68964411]
 [  0.           0.          86.81234454 100.         115.19099102]
 [  0.           0.          75.36383164  86.81234454 100.        ]
 [  0.           0.           0.          75.36383164  86.81234454]
 [  0.           0.           0.          65.42510919  75.36383164]
 [  0.           0.           0.           0.          65.42510919]
 [  0.           0.           0.           0.          56.7970712 ]]`

## Define a function to calculate the European option price using trinomial model

In [11]:
def priceTriEuro(N, K, r, S, p_u, p_d, p_m, d_t):
    
    """
    Function that calculates the European option price using trinomial model
    
    Input: N     -> Number of time periods
           K     -> Strike price
           r     -> Interst rate
           S     -> Upper triangular matrix
           p_u   -> probability for upward movement
           p_d   -> probability for downward movement
           p_m   -> probability for no change
           d_t   -> time step size
       
    Output: C -> European Call option 
            P -> European Put option 
    """
    # Add code here
    #1) Creating empty matrices
    C = np.zeros((2*N + 1, N + 1))
    P = np.zeros((2*N + 1, N + 1))
    #2) Computation of the payoff
    for k in range(0, 2*N + 1):
        if S[k][N]-K <=0: # last column
            C[k][N]=0
        else:
            C[k][N] = S[k][N] - K
        if K-S[k][N]<=0:
            P[k][N]=0
        else:
            P[k][N] = K - S[k][N]
    #3)Backward (value) iteration for options
    for i in range(N-1, -1, -1):   
        for j in range(0,  i*2 + 1):
            C[j][i] = math.exp(-r*d_t) * (p_d*C[j+2][i+1] + p_m*C[j+1][i+1] + p_u*C[j][i+1])
            P[j][i] = math.exp(-r*d_t) * (p_d*P[j+2][i+1] + p_m*P[j+1][i+1] + p_u*P[j][i+1])
    return C, P

In [12]:
# Calculate European call and put values
# Add code here
p_u= 0.2773342477
p_d= 0.2240835697
p_m= 0.4985821826
C, P = priceTriEuro(N, K, r, S, p_u, p_d, p_m, d_t)
print('European Call')
print(C)
print("\n")
print('European Put')
print(P)

European Call
[[10.20509942 20.0925775  35.15865291 54.08873598 76.06541656]
 [ 0.          8.49087322 18.30584773 33.93186407 52.84651603]
 [ 0.          2.35495086  6.54953395 16.43321097 32.68964412]
 [ 0.          0.          1.13955621  4.16064756 15.19099102]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]]


European Put
[[ 5.32804187  1.22102826  0.          0.          0.        ]
 [ 0.          4.810315    0.64584791  0.          0.        ]
 [ 0.         11.86204809  4.08052515  0.          0.        ]
 [ 0.          0.         11.85820287  2.91842761  0.        ]
 [ 0.          0.         22.16715956 11.94543551  0.        ]
 [ 0.          0.          0.         23.39394841 13.18765546]
 [ 0.          0.        

**Expected Output:**

`European Call`

`[[10.20509942 20.0925775  35.15865291 54.08873598 76.06541655]
 [ 0.          8.49087322 18.30584772 33.93186407 52.84651603]
 [ 0.          2.35495086  6.54953395 16.43321097 32.68964411]
 [ 0.          0.          1.13955621  4.16064756 15.19099102]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]]`

`European Put`

`[[ 5.32804187  1.22102826  0.          0.          0.        ]
 [ 0.          4.810315    0.64584791  0.          0.        ]
 [ 0.         11.86204809  4.08052515  0.          0.        ]
 [ 0.          0.         11.85820287  2.91842761  0.        ]
 [ 0.          0.         22.16715956 11.94543551  0.        ]
 [ 0.          0.          0.         23.39394841 13.18765546]
 [ 0.          0.          0.         33.33267086 24.63616836]
 [ 0.          0.          0.          0.         34.57489081]
 [ 0.          0.          0.          0.         43.2029288 ]]`

## Define a function to calculate the American option price using trinomial model

In [13]:
def priceTriAmer(N, K, r, S, p_u, p_d, p_m, d_t):
    """
    Function that calculates the American option price using trinomial model
    
    Input: N     -> Number of time periods
           K     -> Strike price
           r     -> Interst rate
           S     -> Upper triangular matrix
           p_u   -> probability for upward movement
           p_d   -> probability for downward movement
           p_m   -> probability for no change
           d_t   -> time step size
       
    Output: C -> American Call option 
            P -> American Put option 

    """
    # Add code here
    #1) Creating empty matrices
    C = np.zeros((2*N + 1, N + 1))
    P = np.zeros((2*N + 1, N + 1))

    #2) Computation of the payoff
    for k in range(0, 2*N + 1):
        if S[k][N]-K <=0:
            C[k][N]=0
        else:
            C[k][N] = S[k][N] - K
        if K-S[k][N]<=0:
            P[k][N]=0
        else:
            P[k][N] = K - S[k][N]
    # Backward (value) iteration for options
    for i in range(N-1, -1, -1):
        for j in range(0,  i*2 + 1):
            back_C = math.exp(-r*d_t) * (p_d*C[j+2][i+1] + p_m*C[j+1][i+1] + p_u*C[j][i+1])
            C[j][i] = max(S[j][i] - K, back_C)
            back_P = math.exp(-r*d_t) * (p_d*P[j+2][i+1] + p_m*P[j+1][i+1] + p_u*P[j][i+1])
            P[j][i] = max(K - S[j][i], back_P)
    return C, P

In [14]:
# Calculate American call and put values
# Add code here
C, P = priceTriAmer(N, K, r, S, p_u, p_d, p_m, d_t)
print('American Call')
print(C)
print('\n')
print('American Put')
print(P)

American Call
[[10.20509942 20.0925775  35.15865291 54.08873598 76.06541656]
 [ 0.          8.49087322 18.30584773 33.93186407 52.84651603]
 [ 0.          2.35495086  6.54953395 16.43321097 32.68964412]
 [ 0.          0.          1.13955621  4.16064756 15.19099102]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]]


American Put
[[ 5.84957502  1.28186433  0.          0.          0.        ]
 [ 0.          5.23988204  0.64584791  0.          0.        ]
 [ 0.         13.18765546  4.35542837  0.          0.        ]
 [ 0.          0.         13.18765546  2.91842761  0.        ]
 [ 0.          0.         24.63616836 13.18765546  0.        ]
 [ 0.          0.          0.         24.63616836 13.18765546]
 [ 0.          0.        

**Expected Output:**

`American Call`

`[[10.20509942 20.0925775  35.15865291 54.08873598 76.06541655]
 [ 0.          8.49087322 18.30584772 33.93186407 52.84651603]
 [ 0.          2.35495086  6.54953395 16.43321097 32.68964411]
 [ 0.          0.          1.13955621  4.16064756 15.19099102]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]]`

`American Put`

`[[ 5.84957502  1.28186433  0.          0.          0.        ]
 [ 0.          5.23988204  0.64584791  0.          0.        ]
 [ 0.         13.18765546  4.35542837  0.          0.        ]
 [ 0.          0.         13.18765546  2.91842761  0.        ]
 [ 0.          0.         24.63616836 13.18765546  0.        ]
 [ 0.          0.          0.         24.63616836 13.18765546]
 [ 0.          0.          0.         34.57489081 24.63616836]
 [ 0.          0.          0.          0.         34.57489081]
 [ 0.          0.          0.          0.         43.2029288 ]]`

## Comparing European and American option values calculated with Trinomial Model from the exact Solution

In [15]:
# Calculate European and American put values for different N and compare to exact solution
# Exact Values
E_P_ex = 5.5735
A_P_ex = 6.0624
N = [4, 16, 64, 256, 512, 1024]
# Add code here
print('   N    E_P_ex    E_P_app    err_E_P        A_P_ex     A_P_app    err_A_P')
print('-------------------------------------------------------------------------------')
for i in N:
    d_t = T / i
    u, d = calc_ud(sigma, d_t)
    p_u, p_d, p_m = calc_prob(r, sigma, d_t)
    S = stock_price_trinom(S0, i, u, d)
    Const, E_P_app = priceTriEuro(i, K, r, S, p_u, p_d, p_m, d_t)
    Const, A_P_app = priceTriAmer(i, K, r, S, p_u, p_d, p_m, d_t)
    err_E_P = abs(E_P_ex - E_P_app[0][0])
    err_A_P = abs(A_P_ex - A_P_app[0][0])
    print('%4.d   %2.6f   %2.6f   %e   %2.6f   %2.6f   %e' % (i, E_P_ex, E_P_app[0][0], err_E_P, A_P_ex, A_P_app[0][0], err_A_P))

   N    E_P_ex    E_P_app    err_E_P        A_P_ex     A_P_app    err_A_P
-------------------------------------------------------------------------------
   4   5.573500   5.328042   2.454581e-01   6.062400   5.849575   2.128250e-01
  16   5.573500   5.511288   6.221195e-02   6.062400   6.031125   3.127492e-02
  64   5.573500   5.557919   1.558139e-02   6.062400   6.077022   1.462235e-02
 256   5.573500   5.569621   3.878723e-03   6.062400   6.087340   2.493992e-02
 512   5.573500   5.571573   1.926581e-03   6.062400   6.088906   2.650645e-02
1024   5.573500   5.572550   9.503480e-04   6.062400   6.089652   2.725172e-02


**Expected Output:**
![title](trinom_tree.png)

In [65]:
# feel free to use this cell for additional tests

In [ ]:
# feel free to use this cell for additional tests

In [17]:
# feel free to use this cell for additional tests

In [18]:
# feel free to use this cell for additional tests

In [19]:
# feel free to use this cell for additional tests